<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-VCFVK0KI" failures="1" tests="1" name="Test" time="4.191" errors="0" timestamp="2024-10-26T13:04:48 IST">
  <testcase classname="testCases.LoginDDT" name="verify_loginDDT" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3">
      <![CDATA[java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
at utilities.DataProviders.getData(DataProviders.java:26)
... 25 more
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- verify_loginDDT -->
</testsuite> <!-- Test -->
